---
title: "hw_5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 5.1

```{r}
library(tidyverse)
chairs <- read.csv('https://raw.githubusercontent.com/dashapetrova/2019_hse_data_analysis/master/hw5_CA_MCA/hw5_chairs.csv')
MCA <- MASS::mca(chairs[,-1:-3])
chairs <- cbind(chairs, MCA$rs)
variables <- as_data_frame(MCA$cs)
variables$var_names <- rownames(MCA$cs)
chairs %>% 
  ggplot(aes(`1`, `2`))+
  geom_point(aes(color = Category))+
  stat_ellipse(aes(color = Category))+
  geom_text(data = variables, aes(`1`, `2`, label = var_names), size=3)+
  theme_bw()+
  scale_x_continuous()
```

### 5.2

```{r}
'рассматриваемые категории не так сильно пересекаются; некоторые параметры, похоже, характерны для обеих категорий(age.adult), какие-то, наоборот, - ни для одной из них(back.adjust), или же скорее чему-нибудь одному(Arms.No - стул, MaterialSeat.Fabric - кресло)'
```

### 5.3

```{r}
library(ca)
colreg <- read.csv('https://raw.githubusercontent.com/dashapetrova/2019_hse_data_analysis/master/hw5_CA_MCA/hw5_colreg.csv')
rownames(colreg) <- colreg$colors
ca <- ca(colreg[-5])

colreg_col <- data.frame(ca$colcoord)
colreg_col$rows <- rownames(ca$colcoord)

colreg_row <- data.frame(ca$rowcoord)
colreg_row$rows <- rownames(ca$rowcoord)

colreg_col %>% 
  ggplot(aes(Dim1, Dim2, label = rows))+
  geom_text(color = "blue")+
  geom_text(data = colreg_row, color = "red")+
  theme_bw()+
  labs(x = "Dim1 (42.1%)",
       y = "Dim2 (32.6%)")
```

### 5.4

```{r}
'по частотности цветов получается следующая иерархия: fiction, press, spoken, academic - где в художественной литературе больше всего цветов, в академической - меньше всего; black встречаются больше в разговорном языке; white примерно одинаков по употреблению во всех четырех категориях; grey - единственный цвет в некоторой удаленности от всех остальных'
```
